<?php
include 'header.phtml';
?>
      <div class="content">
<h1 class="description">Студия веб-дизайна АНАНАС</h1>
	<div class="description">
	<p>
	C тех пор как мы изучили учебник ОПа, мы делаем качественные
    и высокопрофессиональные веб-приложения на PHP, с ипользованием 
    самых современных фреймворков и мощных объекто-ориентированных возможностей
    этого прекрасного языка. 
   </p>
</p>Вы можете свзаться со мной в скайпу: <span class="contacts">duanjin811</span></p>
</div>
</div>
<?php include 'footer.html'; ?> 