<?php
session_start();
include 'header.phtml';
?>
 <div class="content front">
  <!--
  <h1>Делитесь документами, фотографиями, музыкой и видео.</h1><h2>С <span>Download.me</span> делать это легко и приятно!</h2>
    <p>Выберите файл, которым хотите поделиться:</p>
  -->
    <form id="upload" action="/upload" method="post" enctype="multipart/form-data" class="form-inline">
      <input type="hidden" name="<?= ini_get("session.upload_progress.name"); ?>" value="d-loadme">
      <input type="hidden" name="MAX_FILE_SIZE" value="<?= $maxFileSize ?>">
      <input type="file" name="userfile" id="userfile"/>
      <button type="submit" class="btn btn-primary" data-loading-text="Отправка..." data-complete-text="Готово!" >Отправить</button>
    </form>
    <? if(isset($flash['error'])): ?>
      <div class="alert alert-error fade in">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>Ошибка!</strong> <?= $flash['error'] ?>
      </div>
      <div class="alert alert-info fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        Максимальный размер загружаемого файла - <?= round($maxFileSize/(1024*1024)) ?> Mб 
      </div>
    <? endif; ?>
    <div class="progress progress-striped active">
    <div class="bar" style="width: 0;"></div>
    </div>
        <span class="percents">0%</span>
  </div>
</div>

    </div>

  </div>

  <style type="text/css">
.progress, .percents {
  display: none;
}

.progress {
  width: 50%;
  margin: auto;
}
  </style>
<script type="text/javascript">
/*
$(function() {
 $('#upload').on("submit", function(e) {
   if ($('input[type="file"]', this).val() == "") {
      if ($('.content').has('.alert-error').length == 0) {
       $('<div class="alert alert-error fade in" style="display: none;"></div>')
      .append('<a href="#" class="close" data-dismiss="alert">&times;</a>')
      .append('<strong>Ошибка!</strong> Вы не выбрали файл.')
      .insertAfter(this).slideDown();
    }
    e.preventDefault();
    return false;
   } else {
    return true;
   }
 });
});
*/

$.ajaxSetup({ cache: false });
var t;
progress = function(){
    $.ajax({
        url: '/upload-progress',
        dataType: 'json',
        cache: false,
        success: function(result){
            if(result['percent']) {
              $(".bar").css("width", Math.ceil(result.percent)+"%");
              $(".percents").text(Math.ceil(result.percent)+"%");
                }
            }
        });
    };
$(function() {
    $('#upload').attr('action', '/upload/async'); 
    $('#upload').ajaxForm({
        type: 'POST',
        dataType: "json",
        success: function(result) { 
            clearInterval(t);
            $(".bar").css("width", "100%");
            $(".percents").text("100%");
            $('button[type="submit"]').button('complete');
            window.location.replace("/f/"+result['id']);
        },
        beforeSubmit: function(arr, form, options) {
             if ($('input[type="file"]', form).val() == "") {
               if ($('.content').has('.alert-error').length == 0) {
                 $('<div class="alert alert-error fade in" style="display: none;"></div>')
                 .append('<a href="#" class="close" data-dismiss="alert">&times;</a>')
                   .append('<strong>Ошибка!</strong> Вы не выбрали файл.')
                     .insertAfter(form).slideDown();
               }
            return false;
            } else {
                $(".progress, .percents").show();
                $('button[type="submit"]').button('loading');
                $('input[type="file"]').attr("disabled", "");
                t = setInterval("progress()", 1000);
          }
        }
   });
});
</script>
<? 
include 'footer.html'; 
?>
