<?php
session_start();
include 'header.phtml';
?>
 <div class="content">
  <h1>Делитесь документами, фотографиями, музыкой и видео.</h1><h2>С <span>Download.me</span> делать это легко и приятно!</h2>
    <p>Выберите файл, которым хотите поделиться:</p>
    <form id="upload" action="/upload" method="post" enctype="multipart/form-data">
      <input type="hidden" name="<?= ini_get("session.upload_progress.name") ?>" value="d-loadme">
      <input type="hidden" name="MAX_FILE_SIZE" value="100000000">
      <input type="file" name="userfile" id="userfile"/>
      <button type="submit" class="btn btn-primary" data-loading-text="Отправка...">Отправить</button>
      <p class="error message"><?= $errorMessage ?></p>
    </form>
    <div id="upload_progress" class="progress progress-striped active">
    <div class="bar" style="width: 0%;"></div>
    </div>
  </div>
<script type="text/javascript">

var t;
progress = function(){
    $.ajax({
        url: '/upload-progress',
        dataType: 'json',
        success: function(data){
            if(data.percent) {
                 $('.bar', '#upload-progress').css('width', data.percent+'%');
            }
        }
    });
}

$(function() {
    $('#upload').attr('action', '/upload/async'); 
    $('#upload').ajaxForm({
        type: 'POST',
        success: function(data) { 
            clearTimeout(t);
            $('button[type="submit"]').button('reset');
             alert("Done!");
        },
        beforeSubmit: function() {
            $('button[type="submit"]').button('loading');
            $('#upload_progress').show();
            t = setTimeout(function go() {
                  progress();
                  setTimeout(go, 300);
                }, 300);
        }
   });

});

</script>

<? 
include 'footer.html'; 
?>
