<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?></title>
<link href="/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
<style>body{padding-top:60px; }</style>
<link href="/vendor/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
<link type="text/css" href="/vendor/jPlayer/skin/jplayer.blue.monday.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/styles/main.css">
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<link rel="icon" type="image/vnd.microsoft.icon" href="/assets/ico/favicon.ico">
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="/vendor/jquery.form.min.js"></script>
    <script type="text/javascript" src="/vendor/jplayer/js/jquery.jplayer.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Download.me - файлообменник</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><a href="/">Загрузить файл</a></li>
          <li><a href="/files">Последние файлы</a></li>
          <li><a href="/about">О нас</a></li>
        </ul>
      </div>
      <form class="navbar-search pull-right" method="GET" action="/search">
      <input type="text" class="search-query" placeholder="Поиск" name="string">
      </form>
    </div>
  </div>
</div>
<div class="container">

